//AUTOGENERATED FILE FROM png2mtspr
#define square_TILE_H 8
#define square_WIDTH 16
#define square_HEIGHT 16
#define square_PIVOT_X 8
#define square_PIVOT_Y 8

extern const UINT8 square_data[64];
extern const metasprite_t* const square_metasprites[1];
